name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 5.13.0

dependencies:
  async: 2.11.0
  dartx: 1.0.0
  flutter:
    sdk: flutter
  get_it: 7.6.0
  injectable: 2.1.2
  meta: 1.9.1
  resources:
    path: ../resources
  rxdart: 0.26.0
  shared:
    path: ../shared
  tuple: 2.0.0

dev_dependencies:
  build_runner: 2.4.5
  dart_code_metrics: 5.7.5

  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  injectable_generator: 2.1.6
  mocktail: 0.3.0
